### ISSUE TITLE
Option to skip printing each file's hash string, and only print md5 hash value of the hash string

### ISSUE THREAD

**Issue by vorburger** [fcivaner/hashdir#1]
I would like to use this for https://github.com/enola-dev/enola/issues/753, instead of https://github.com/stiction/hash-dir or https://ultimateanu.github.io/hashdir/, but in order to be able to use it in a script to save and then later compare the final hash, I need it to  have an option to skip printing each file's hash string, and only print md5 hash value of the hash string.

**Comment by vorburger** [comment]
Oh wow wait, you [do have a `--quiet` option](https://github.com/fcivaner/hashdir/commit/74a5ff7319fc02ff5f9a63c51771fbfface446ec), shown by `hashdir -h` - I just didn't notice it at first, due to the README not mentioning it! 

I'll send you a PR to add that missing doc. 

PS: Use https://docs.enola.dev/use/execmd/ to auto-update your README! 🤣

**Comment by fcivaner** [comment]
Thank you, yes, as you mentioned it seems like I haven't updated the README file. Merged, I'll also check how enola works :)
